#!/bin/bash

function wait_for_socket {
    source /scripts/init_node_vars

    if [[ -z "$(get_slot 2>/dev/null)" ]]; then
        echo -e "\nWaiting for cardano-node to read the blockchain and start the socket."
        echo -n "It may take a while. Trying again."
        sleep 5

        while true; do
            if [[ -z "$(get_slot 2>/dev/null)" ]]; then
                echo -n "."
                sleep 5
            else
                break
            fi
        done

        echo -e "${CHECK_MARK} Socket is now functional."
    fi
}
