#!/bin/bash

function wait_for_sync {
    source /scripts/functions/wait_for_socket
    wait_for_socket
    WAIT_FOR_SYNC=$1

    echo -e "\nWaiting for cardano-node to sync to at least ${WAIT_FOR_SYNC}%"
    echo -n ""

    while true; do
        SYNC_PCT=$(sync_status | tr ' ' '\n' | tail -1 | sed 's/%//g' | bc)
        echo -en "\\r== $(sync_status) "

        if [[ (($SYNC_PCT > $WAIT_FOR_SYNC)) ]]; then
            echo -e "${CHECK_MARK} Done."
            break
        fi
        sleep 5
    done
}
