#!/bin/bash

topology="./new-scripts/block-producing-configs/ff-topology.json"
config="./new-scripts/block-producing-configs/ff-config.json"

echo "topology: $topology"
echo "config: $config"

 cardano-node run \
     --topology $topology \
     --database-path block-producing/db \
     --socket-path /db/node.socket \
     --host-addr 127.0.0.1 \
     --port 8080 \
     --config $config