#!/bin/bash

source /scripts/init_node_vars

# Init vars
POOL_ID=$(cat ${NODE_PATH}/staking/POOL_ID)
BYRON_GENESIS=${NODE_PATH}/byron-genesis.json
SHELLEY_GENESIS=${NODE_PATH}/shelley-genesis.json
VRF=${NODE_PATH}/staking/pool-keys/vrf.skey
SNAPSHOT=/tmp/stake-snapshot.json
LSET="${1:-current}"

case ${LSET} in
  prev|current|next) echo "Running leaderlogs for ${LSET} epoch" ;;
  *)                 echo "Invalid argument. Must be either prev|current|next"; exit ;;
esac

echo "Generating snapshot"
cardano-cli query stake-snapshot --stake-pool-id ${POOL_ID} ${NETWORK_ARGUMENT} > ${SNAPSHOT}
ACTIVE_STAKE=$(cat $SNAPSHOT | jq .activeStakeSet)
POOL_STAKE=$(cat $SNAPSHOT | jq .poolStakeSet)

# Get leaderlogs
echo "Running leaderlogs"
cncli leaderlog --db ${NODE_PATH}/cncli.db \
  --pool-id ${POOL_ID} \
  --pool-vrf-skey ${VRF} \
  --byron-genesis ${BYRON_GENESIS} \
  --shelley-genesis ${SHELLEY_GENESIS} \
  --active-stake ${ACTIVE_STAKE} \
  --pool-stake ${POOL_STAKE} \
  --ledger-set ${LSET} | tee ${NODE_PATH}/leaderlog_cncli.json