#!/bin/bash

source /scripts/init_node_vars

# Init vars
POOL_ID=$(cat ${NODE_PATH}/staking/POOL_ID)
VRF=${NODE_PATH}/staking/pool-keys/vrf.skey
LSET="${1:-current}"

case ${LSET} in
  current) EPOCH=$(current_epoch) ;;
  next)    EPOCH=$(($(current_epoch)+1)) ;;
  *)       echo "Invalid argument. Must be either current|next"; exit ;;
esac

echo "Running leaderlogs for ${LSET} epoch ${EPOCH}"

mkdir -p ${NODE_PATH}/leaderlogs

cardano-cli query leadership-schedule \
   ${NETWORK_ARGUMENT} \
   --genesis ${NODE_PATH}/shelley-genesis.json \
   --stake-pool-id ${POOL_ID} \
   --vrf-signing-key-file ${VRF} \
   --${LSET} | tee ${NODE_PATH}/leaderlogs/${EPOCH}.txt
