#!/bin/bash

# From Documentation
# https://github.com/input-output-hk/cardano-tutorials/blob/master/node-setup/080_register_stakepool.md

# Init vars
source /scripts/functions/check_balance
source /scripts/functions/check_pool_registration
source /scripts/functions/wait_for_pool_registration
source /scripts/functions/wait_for_slot
source /scripts/functions/wait_for_sync
source /scripts/init_node_vars
TIMESTAMP=$(date +%s)
PROTOCOL_PARAMS_FILE=${NODE_PATH}/staking/protocol.json

# Enter staking directory
cd ${NODE_PATH}/staking/
mkdir -p wallets/owner/transactions

echo ""
echo "Submitting stake pool certificates to the blockchain."

# Check for required files
if [ ! -f "wallets/owner/stake.skey" ]; then
    echo "Missing required wallets/${WALLET}/stake.skey. You need to run \`generate_wallet owner\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "wallets/owner/payment.skey" ]; then
    echo "Missing required wallets/${WALLET}/payment.skey. You need to run \`generate_wallet owner\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "wallets/owner/payment.addr" ]; then
    echo "Missing required wallets/${WALLET}/payment.addr. You need to run \`generate_wallet owner\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "cold-keys/cold.skey" ]; then
    echo "Missing required staking/cold-keys/cold.skey. You need to run \`generate_operational_certificate\` to generate this key."
    MISSING_FILES=1
fi

if [ ! -f "pool.cert" ]; then
    echo "Missing required staking/pool.cert. You need to run \`generate_registration_certificate\` to generate this certificate."
    MISSING_FILES=1
fi

if [ ! -f "wallets/owner/delegation.cert" ]; then
    echo "Missing required staking/wallets/owner/delegation.cert. You need to run \`generate_registration_certificate\` to generate this certificate."
    MISSING_FILES=1
fi

if [ -n "$MISSING_FILES" ]; then
    exit
fi

# Handle arguments
for i in "$@"
do
case $i in
    --update)
        UPDATE=1
    ;;
    --no_deleg)
        NO_DELEG=1
    ;;
    --cold-create)
        COLD_CREATE=1
    ;;
esac
done

# Wait for node to sync
if [[ "${WAIT_FOR_SYNC}" == "True" ]]; then
    wait_for_sync 99.90
fi

# Generate protocol
if [ -z "$COLD_CREATE" ]; then
    cardano-cli latest query protocol-parameters \
        ${NETWORK_ARGUMENT} \
        --out-file ${PROTOCOL_PARAMS_FILE}
else
    if [ ! -f "${PROTOCOL_PARAMS_FILE}" ]; then
        read -n 1 -r -s -p "Missing ${PROTOCOL_PARAMS_FILE}. You must transfer this file from an online node. Press ENTER when you have placed the file and are ready to continue."
    fi
fi

# Get pool-deposit
if [ -z "$UPDATE" ]; then
    POOL_DEPOSIT=$(jq -r .stakePoolDeposit ${PROTOCOL_PARAMS_FILE})
else
    POOL_DEPOSIT=0
fi


ADDRESS=$(cat wallets/owner/payment.addr)

# Find UTXO in address with enough lovelace to do the transaction
if [ -z "$COLD_CREATE" ]; then
    check_balance $(expr ${POOL_DEPOSIT})
    SLOT=$(get_slot)
else
    read -p "Enter the current tip slot: " SLOT
fi

TTL=$(expr ${SLOT} + 500)

# Multiowners delegation certificates
if [ -n "$MULTI_OWNERS" ]; then
    echo "Multiple owner delegation certificates"
    MULTIOWNER_COUNT=0
    for i in $(echo ${MULTI_OWNERS} | sed "s/,/ /g")
    do
        echo "$i"
        MULTIOWNERS_CERT_STRING="${MULTIOWNERS_CERT_STRING} --certificate-file wallets/$i/delegation.cert"
        MULTIOWNERS_SIGN="${MULTIOWNERS_SIGN} --signing-key-file wallets/$i/stake.skey"
        MULTIOWNER_COUNT=$(expr ${MULTIOWNER_COUNT} + 1)
    done
    echo $MULTIOWNERS_CERT_STRING
    echo $MULTIOWNERS_SIGN
fi

if [ -z "$NO_DELEG" ]; then
    DELEG_CERTS="--certificate-file wallets/owner/delegation.cert ${MULTIOWNERS_CERT_STRING}"
fi

WITNESS_COUNT=$(expr 3 + ${MULTIOWNER_COUNT:-0})

# Draft transaction
cardano-cli latest transaction build-raw \
    --tx-in "${UTXO}#${TXIX}" \
    --tx-out ${ADDRESS}+$(expr ${LOVELACE} - ${POOL_DEPOSIT}) \
    --ttl ${TTL} \
    --fee 0 \
    --out-file wallets/owner/transactions/register_stake_pool.draft \
    --certificate-file pool.cert ${DELEG_CERTS}


## Calculate the fee
FEE=$(
    cardano-cli latest transaction calculate-min-fee \
        --tx-body-file wallets/owner/transactions/register_stake_pool.draft \
        --tx-in-count 1 \
        --tx-out-count 1 \
        --witness-count ${WITNESS_COUNT} \
        --byron-witness-count 0 \
        ${NETWORK_ARGUMENT} \
        --protocol-params-file ${PROTOCOL_PARAMS_FILE} \
    | jq -r '.fee')

TOTAL_PRICE=$(expr ${FEE} + ${POOL_DEPOSIT})

echo "Fee is: ${FEE} Lovelace"
echo "Pool-Deposit: ${POOL_DEPOSIT} Lovelace"
echo "Total Price is: ${TOTAL_PRICE} Lovelace"


# Display transaction info
REMAINING_AFTER_TX=$(expr ${LOVELACE} - ${TOTAL_PRICE})
echo "Creating transaction"
echo "Lovelace after transaction: ${REMAINING_AFTER_TX}"
echo "Current tip Slot: ${SLOT}"
echo "TTL: ${TTL}"

#
# Create the transaction
#
echo "Create transaction"
cardano-cli latest transaction build-raw \
    --tx-in "${UTXO}#${TXIX}" \
    --tx-out ${ADDRESS}+${REMAINING_AFTER_TX} \
    --ttl ${TTL} \
    --fee ${FEE} \
    --out-file wallets/owner/transactions/register_stake_pool.raw \
    --certificate-file pool.cert ${DELEG_CERTS}

# Sign the transaction
echo "Sign transaction"
cardano-cli latest transaction sign \
    --tx-body-file wallets/owner/transactions/register_stake_pool.raw \
    --signing-key-file wallets/owner/payment.skey \
    --signing-key-file wallets/owner/stake.skey \
    ${MULTIOWNERS_SIGN} \
    --signing-key-file cold-keys/cold.skey \
    ${NETWORK_ARGUMENT} \
    --out-file wallets/owner/transactions/register_stake_pool.signed


# Submit the transaction
if [ -z "$COLD_CREATE" ]; then
    read -n 1 -r -s -p $'Press enter to submit the certificates...\n'

    echo "Submit transaction"
    OUT=$(cardano-cli latest transaction submit \
        --tx-file wallets/owner/transactions/register_stake_pool.signed \
        ${NETWORK_ARGUMENT} 2>&1)

    if [[ $OUT =~ "Error" ]]
    then
        echo "An error occoured."
        echo ${OUT}
        read
    else
        echo "Transaction has been submitted to the blockchain."
        echo ${OUT}

        # Wait for blockchain to register the pool
        #wait_for_slot ${TTL}
        #wait_for_pool_registration
        echo "Your stake pool registration has been sent to the blockchain."
        touch ${NODE_PATH}/staking/wallets/owner/transactions/register_stake_pool.submitted
    fi
fi
