#!/bin/bash

source /scripts/init_node_vars

POOL_ID=$(cat ${NODE_PATH}/staking/POOL_ID)
VRF=${NODE_PATH}/staking/pool-keys/vrf.skey
BYRON_GENESIS=${NODE_PATH}/byron-genesis.json
SHELLEY_GENESIS=${NODE_PATH}/shelley-genesis.json
SNAPSHOT=/tmp/stake-snapshot.json

cncli sendslots --db ${NODE_PATH}/cncli.db --byron-genesis ${BYRON_GENESIS} --shelley-genesis ${SHELLEY_GENESIS} --config ${NODE_PATH}/pooltool.json