#!/bin/bash -l

for i in "$@"; do
  case $i in
      --auto-restart)
        AUTO_RESTART=1
      ;;
      --retry)
        RETRY=1
      ;;
  esac
done

source /scripts/functions/get_public_ip

cd ${NODE_PATH}

echo -n "Updating topology.json ..."

NWMAGIC=$(jq -r .networkMagic < ${NODE_PATH}/shelley-genesis.json)
CUSTOM_PEERS=$(python3 /scripts/get_topology_str.py)

curl -s -o ${NODE_PATH}/topology.auto.json "https://api.clio.one/htopology/v1/fetch/?max=14&magic=${NWMAGIC}&customPeers=${CUSTOM_PEERS}"
PRODUCERS=$(jq -r .Producers < ${NODE_PATH}/topology.auto.json)

if [[ "${PRODUCERS}" == "null" ]]; then
    echo " ${CROSS_MARK} Error."
    cat ${NODE_PATH}/topology.auto.json

    if [[ -n "$RETRY" ]]; then
        echo "Submitting IP to topology updater database and retrying fetching the topology."
        topology_submit
        topology_update
    fi
else
    # Replace topology
    mv ${NODE_PATH}/topology.json ${NODE_PATH}/topology.backup.json
    mv -f ${NODE_PATH}/topology.auto.json ${NODE_PATH}/topology.json

    echo -e " ${CHECK_MARK} Done."

    # Restart cardano-node
    if [[ -n "$AUTO_RESTART" ]]; then
        echo -en "\nRestarting cardano-node ..."
        killall -9 cardano-node
        echo -e " ${CHECK_MARK} Done."
    fi
fi
